name: graduated_proj
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.0.0-nullsafety.2




  file_picker: ^3.0.0  # Updated file_picker to a compatible version
  image_picker: ^0.8.0+2
  flutter_animated_icons: ^1.0.0
  awesome_dialog: ^3.1.0
  shared_preferences: ^2.2.2
  custom_text: ^1.1.0
  url_launcher: ^6.2.4
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  flutter_localizations:
    sdk: flutter
  flutter_full_pdf_viewer_null_safe: ^1.0.0
  webview_flutter: ^4.5.0
  dio: ^5.4.2+1
  open_filex: ^4.4.0
  http: ^1.1.0
  path: ^1.8.3
  intl: ^0.18.1
  flutter_downloader: ^1.11.7
  path_provider: ^2.1.3
  visibility_detector: ^0.4.0+2
  font_awesome_flutter: ^10.7.0



  # shared_preferences: ^2.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
